-
  environment:
    coveralls_token:
      secure: SUUjAf0h5IiK+9NOJuLJheUwkAQZiC9Bf1/zZE0/oc3LOEoliMq+KNJdCB9BcdaI

  init:
  - git config --global core.autocrlf true 
  - dir "C:\Program Files (x86)\"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\"

  install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
  - choco install -y psake

  before_build:
  - ps: psake .\build.tasks.ps1 RestoreNuGetPackages

  build_script:
  - ps: psake .\build.tasks.ps1 Build

  test_script:
  - ps: psake .\build.tasks.ps1 AppVeyor-TestAndPublishCodeCoverage

-
  branches:
    only:
      - coverity_scan

  environment:
    coverity_token:
      secure: 7PGMsWzSkiLFkgLSio/rVWCUGDFWBY3no64BMmr3sq0=
    coverity_email:
      secure: KGjFoFTNOGBGQgS2D4f+m5bdUq5LJDoE38plBnK5EjY=

  init:
  - git config --global core.autocrlf true

  before_build:
  - nuget restore

  build_script:
  - cov-build --dir cov-int msbuild "Gesetzesentwicklung-Tool.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  test: off

  deploy_script:
  - nuget install -ExcludeVersion PublishCoverity
  - PublishCoverity\PublishCoverity.exe compress -o coverity.zip -i cov-int
  - PublishCoverity\PublishCoverity.exe publish -t %coverity_token% -e %coverity_email% -r chkpnt/Gesetzesentwicklung-Tool -z coverity.zip --codeVersion %APPVEYOR_BUILD_VERSION%